project_id = "qvpnfxssfhfxqqkbmahw"

[functions.get-mapbox-token]
verify_jwt = false

[functions.admin-create-portal-user]
verify_jwt = false

[functions.scrape-supplier-prices]
verify_jwt = false

[functions.get-docket]
verify_jwt = false

[functions.send-ops-report]
verify_jwt = false